Fix fallback to default `SPARK_LOG_EXT` value
Recent change (https://github.com/linkedin/dr-elephant/pull/79) broke the build:

```
[error] /tmp/dr-elephant/app/org/apache/spark/deploy/history/SparkFSFetcher.scala:240: value getOrDefault is not a member of java.util.Map[String,String]
[error]             val sparkLogExt = fetcherConfData.getParamMap.getOrDefault(SPARK_LOG_EXT, defSparkLogExt)
[error]                                                           ^
```